version: '3'
services:
  sql:
    image: kcarre/sql:latest
    container_name: sql
    ports:
      - "3306:3306"
    networks:
      - flowernetwork
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: flowerDB
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

  flowerexpress:
    image: kcarre/flowerexpress:latest
    container_name: flowerexpress
    ports:
      - "5000:5000"
    networks:
      - flowernetwork
    depends_on:
      - sql

  webshop-front:
    image: kcarre/webshop-front-image:latest
    container_name: webshop-front
    ports:
      - "3000:3000"
    networks:
      - flowernetwork

networks:
  flowernetwork:
    driver: bridge
