version: '3'
services:
  webshop-front:
    image: webshop-front-image
    build:
      context: ./site
      dockerfile: Dockerfile
    ports:
      - "8080:3000"

  webshop-back:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - webshop-app_mysql-data:/var/lib/mysql